title: "WI+RE"
description: Quick and practical research and writing strategies, collaboratively designed by students, teachers, and librarians at UCLA.

url: https://uclalibrary.github.io
baseurl: "/research-tips"
paginate_path: "blog/page:num/"
permalink: :title/

# Collections
collections:
    embeds:
        output: true
        permalink: /embeds/:path/
    cats:
        output: true
        permalink: /categories/:path/
        
# Defaults
defaults:
  - scope:
      path: ""
      type: cats
    values:
      layout: "category"

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: uclalibrary
   twitter: WIREbruin
   facebook: WIREbruin
#   email: 

# google_analytics: "UA-"

plugins:
  - jekyll-seo-tag
